sudo: required
dist: trusty
language: generic
services: docker

script:
  - sudo service docker restart
  - cd ${TRAVIS_BUILD_DIR}
  - travis_wait 45 make ${SUBDIR}

before_deploy:
  - docker login --username=$DOCKER_HUB_USERNAME --password=$DOCKER_HUB_PASSWORD

deploy:
  provider: script
  script: make push_${SUBDIR}
  on:
    branch: master

notifications:
  email:
    on_success: change
    on_failure: change

matrix:
  include:
  - env: SUBDIR=debian_travis
  # disabled since it does not complete within travis' time limits
  # - env: SUBDIR=manylinux
  - env: SUBDIR=arch
  - env: SUBDIR=testing
